config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles, only: %i[show index new create edit update]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base # rubocop:disable Style/Documentation
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

class ArticlesController < ApplicationController # rubocop:disable Style/Documentation
  def show
    @article = Article.find(params[:id])
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params.require(:article).permit(:title, :description))
    if @article.save
      flash[:notice] = 'Succesfully Created an Article'
      redirect_to @article
    else
      render 'new'
    end
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(params.require(:article).permit(:title, :description))
      flash[:notice] = 'Successfully Updated an Article'
      redirect_to @article
    else
      render 'edit'

    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController # rubocop:disable Style/Documentation
  def home; end
  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>
<% if @article.errors.any? %>
    <h2>The following errors occured</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
            <% end %>
    </ul>
    <% end %>

        <%= form_with(model: @article,local: true) do |f| %>
            <p>
                <%= f.label :title %><br>
                    <%= f.text_field :title %>
            </p>
            <p>
                <%= f.label :description %><br>
                    <%= f.text_area :description %>
            </p>
            <p>
                <%= f.submit %>
            </p>
            <% end %>

app/views/articles/index.html.erb
<h1>List of Articles</h1>
<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <% @articles.each do |article| %>
            <tr>
                <td>
                    <%= article.title %>
                </td>
                <td>
                    <%= article.description %>
                </td>
            </tr>
            <% end %>
    </tbody>
</table>

app/views/articles/new.html.erb
<h1>Create a new Article</h1>
<% if @article.errors.any? %>
    <h2>The following errors occured</h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
            <% end %>
    </ul>
    <% end %>

        <%= form_with scope: :article, url: articles_path, local: true do |f| %>
            <p>
                <%= f.label :title %><br>
                    <%= f.text_field :title %>
            </p>
            <p>
                <%= f.label :description %><br>
                    <%= f.text_area :description %>
            </p>
            <p>
                <%= f.submit %>
            </p>
            <% end %>

app/views/articles/show.html.erb
<h1>Show Articles with Description</h1>
<p><strong>Title: </strong>
    <%= @article.title %>
</p>
<p><strong>Description: </strong>
    <%= @article.description %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>AplhaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
        <%= csp_meta_tag %>

            <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
                <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <% flash.each do |name,msg|  %>
        <%= msg %>
            <% end %>
                <%= yield %>
</body>

</html>

app/views/pages/about.html.erb
<h1>This is the About Page</h1>

app/views/pages/home.html.erb
<h1>This is the Home Page </h1>